-- =====================================================
-- Fix the notify_inquiry_reply() function
-- SUPERSEDED by: migrations/013_fix_inquiry_reply_trigger.sql
-- This file is kept for reference only. Do NOT run this file.
-- =====================================================
-- The original version had wrong column names for Notification_Tbl:
--   "type" (should be "notificationType")
--   "message", "replyID", "inquiryID" (don't exist in the table)
-- See migration 013 for the corrected version.
