/**
 * Report Export Utility (SE2 revision #7)
 *
 * Produces downloadable reports from dashboard statistics in CSV or
 * spreadsheet-compatible (Excel-friendly) format. Addresses panel feedback
 * that "numbers are wasted if there is no destination" — the system is now
 * capable of producing reports exported from any dashboard view.
 *
 * Usage:
 *   ReportExport.downloadCSV('sk-dashboard-report', [
 *     { label: 'Total Files', value: 128 },
 *     { label: 'Active Projects', value: 7 },
 *   ]);
 *
 * Or with grouped sections:
 *   ReportExport.downloadCSV('report', {
 *     'Overview': [{ label: 'X', value: 1 }],
 *     'Projects': [{ label: 'Y', value: 2 }],
 *   });
 */
(function (global) {
  'use strict';

  function csvEscape(v) {
    if (v === null || v === undefined) return '';
    const s = String(v);
    // Quote if contains comma, quote, newline, or carriage return.
    if (/[",\r\n]/.test(s)) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  }

  function buildCSV(title, payload, meta) {
    const lines = [];
    // Report header block
    lines.push(csvEscape(title));
    lines.push(csvEscape('Generated: ' + new Date().toLocaleString()));
    if (meta && meta.generatedBy) {
      lines.push(csvEscape('Generated by: ' + meta.generatedBy));
    }
    if (meta && meta.source) {
      lines.push(csvEscape('Source: ' + meta.source));
    }
    lines.push(''); // blank line

    if (Array.isArray(payload)) {
      // Flat list of metrics
      lines.push(['Metric', 'Value'].map(csvEscape).join(','));
      for (const row of payload) {
        lines.push([row.label, row.value].map(csvEscape).join(','));
      }
    } else if (payload && typeof payload === 'object') {
      // Grouped sections
      for (const section of Object.keys(payload)) {
        lines.push(csvEscape('[' + section + ']'));
        const rows = payload[section] || [];
        if (rows.length && typeof rows[0] === 'object' && !('label' in rows[0])) {
          // Tabular rows — use object keys as headers.
          const headers = Object.keys(rows[0]);
          lines.push(headers.map(csvEscape).join(','));
          for (const row of rows) {
            lines.push(headers.map((h) => csvEscape(row[h])).join(','));
          }
        } else {
          lines.push(['Metric', 'Value'].map(csvEscape).join(','));
          for (const row of rows) {
            lines.push([row.label, row.value].map(csvEscape).join(','));
          }
        }
        lines.push('');
      }
    }

    return lines.join('\r\n');
  }

  function downloadBlob(filename, mime, content) {
    // BOM prefix so Excel opens UTF-8 CSV correctly.
    const blob = new Blob(['\uFEFF', content], { type: mime + ';charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  function todayStamp() {
    const d = new Date();
    const pad = (n) => String(n).padStart(2, '0');
    return (
      d.getFullYear() +
      pad(d.getMonth() + 1) +
      pad(d.getDate()) +
      '_' +
      pad(d.getHours()) +
      pad(d.getMinutes())
    );
  }

  const ReportExport = {
    /**
     * @param {string} baseName file name base, e.g. "sk-dashboard-report"
     * @param {object|array} payload metrics (see module docs)
     * @param {object} [options] { title, meta, format: 'csv'|'xls' }
     */
    download(baseName, payload, options) {
      options = options || {};
      const format = options.format === 'xls' ? 'xls' : 'csv';
      const title = options.title || 'BIMS Report';
      const csv = buildCSV(title, payload, options.meta);
      const filename = baseName + '_' + todayStamp() + '.' + format;
      const mime = format === 'xls' ? 'application/vnd.ms-excel' : 'text/csv';
      downloadBlob(filename, mime, csv);
    },

    downloadCSV(baseName, payload, options) {
      this.download(baseName, payload, Object.assign({}, options, { format: 'csv' }));
    },

    downloadXLS(baseName, payload, options) {
      this.download(baseName, payload, Object.assign({}, options, { format: 'xls' }));
    },
  };

  global.ReportExport = ReportExport;
})(window);
